name: Deploy Strategy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["Hola", "Pato", "Bootcamp Github Action"]

    steps:
      - name: Print mensaje
        run: echo "${{ matrix.message }}"